/**
 * 主壳 / 下页面静态导出，与路由同步引入以打入主 chunk，减少按页懒加载带来的跳转等待与隧道场景下的连接数。
 */
export { default as DiscoverView } from '../views/DiscoverView.vue'
export { default as MarketView } from '../views/MarketView.vue'
export { default as PublishView } from '../views/PublishView.vue'
export { default as ChatListView } from '../views/ChatListView.vue'
export { default as GroupEditView } from '../views/GroupEditView.vue'
export { default as GroupChatView } from '../views/GroupChatView.vue'
export { default as NoticeCategoryView } from '../views/NoticeCategoryView.vue'
export { default as ChatThreadView } from '../views/ChatThreadView.vue'
export { default as ProfileView } from '../views/ProfileView.vue'
export { default as DailySignView } from '../views/DailySignView.vue'
export { default as FollowListView } from '../views/FollowListView.vue'
export { default as UserProfileView } from '../views/UserProfileView.vue'
export { default as SettingsView } from '../views/SettingsView.vue'
export { default as CartView } from '../views/CartView.vue'
export { default as OrdersView } from '../views/OrdersView.vue'
export { default as OrderDetailView } from '../views/OrderDetailView.vue'
export { default as CouponsView } from '../views/CouponsView.vue'
export { default as WalletView } from '../views/WalletView.vue'
export { default as ProductFootprintView } from '../views/ProductFootprintView.vue'
export { default as ProductSaveView } from '../views/ProductSaveView.vue'
export { default as ProductManageView } from '../views/ProductManageView.vue'
